### ISSUE TITLE
Applicable License?

### ISSUE THREAD

**Issue by yashkhatri** [labra/rbe#1]
Hi Jose,

The License file in this repository says the license applicable is: "GNU Lesser General Public License v3.0" https://github.com/labra/rbe/blob/master/LICENSE

While on Bintray it says MPL-2.0
https://bintray.com/labra/maven/rbe

Can you please look into it?

**Comment by yashkhatri** [comment]
@labra

**Comment by labra** [comment]
I have changed the license to MIT. 

I changed also the license in [bintray](https://bintray.com/labra/maven/rbe). 

Notice, however, that the source code in this repository is not actively maintained as it has been integrated as a [shaclex module](https://github.com/labra/shaclex/tree/master/modules/rbe).
